# Generated by Django 4.2.7 on 2023-12-02 19:57

import api.models.community
import api.models.projects
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('grp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grp_name', models.CharField(max_length=50)),
                ('created_at_date', models.CharField(default='3rd December 2023', max_length=225, null=True)),
                ('created_at_time', models.CharField(default='01:27:18 am', max_length=225, null=True)),
                ('grp_admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('grp_members', models.ManyToManyField(blank=True, default=None, null=True, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=api.models.projects.__learning__resource__path__)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.CharField(blank=True, default='3rd December 2023 01:27:18 am', editable=False, max_length=255, null=True)),
                ('end_date', models.CharField(blank=True, default='3rd December 2023 01:27:18 am', editable=False, max_length=255, null=True)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('project_doc', models.FileField(blank=True, null=True, upload_to=api.models.projects.__prd__file__path__)),
                ('related_techstacks', models.JSONField(blank=True, default=list, editable=False, null=True)),
                ('created_at', models.CharField(blank=True, default='3rd December 2023 01:27:18 am', editable=False, max_length=255, null=True)),
                ('updated_at', models.CharField(blank=True, default='3rd December 2023 01:27:18 am', editable=False, max_length=255, null=True)),
                ('created_by', models.ManyToManyField(blank=True, default=None, null=True, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('learning_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.learningresource')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequirementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_overview', models.TextField()),
                ('original_requirements', models.TextField()),
                ('project_goals', models.TextField()),
                ('user_stories', models.TextField()),
                ('system_architecture', models.TextField()),
                ('requirements_analysis', models.TextField()),
                ('requirement_pool', models.TextField()),
                ('ui_ux_design', models.TextField()),
                ('development_methodology', models.TextField()),
                ('security_measures', models.TextField()),
                ('testing_strategy', models.TextField()),
                ('scalability_and_performance', models.TextField()),
                ('deployment_plan', models.TextField()),
                ('maintenance_and_support', models.TextField()),
                ('risks_and_mitigations', models.TextField()),
                ('compliance_and_regulations', models.TextField()),
                ('budget_and_resources', models.TextField()),
                ('timeline_and_milestones', models.TextField()),
                ('communication_plan', models.TextField()),
                ('anything_unclear', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.CharField(blank=True, default='3rd December 2023 01:27:18 am', editable=False, max_length=255, null=True)),
                ('updated_at', models.CharField(blank=True, default='3rd December 2023 01:27:18 am', editable=False, max_length=255, null=True)),
                ('created_by', models.ManyToManyField(null=True, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, default=list, editable=False, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('no_projects_completed', models.IntegerField(default=0)),
                ('deadline_missed', models.IntegerField(default=0)),
                ('project_cancelled', models.IntegerField(default=0)),
                ('currently_working_on', models.ManyToManyField(null=True, related_name='current_projects_of_talent', to='api.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('project_completion_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('milestone_accomplished', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Mentor', 'Mentor'), ('Member', 'Member'), ('Leader', 'Leader'), ('Client', 'Client')], default='Member', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='prd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRD', to='api.projectrequirementdocument'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('images', models.JSONField(blank=True, default=list, editable=False, null=True)),
                ('date', models.CharField(blank=True, default='3rd December 2023 01:27:18 am', editable=False, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=api.models.community.__post__path__)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, default=list, editable=False, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('no_projects_mentored', models.IntegerField(default=0)),
                ('currently_mentoring', models.ManyToManyField(null=True, related_name='current_projects_of_mentor', to='api.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at_date', models.CharField(default='3rd December 2023', max_length=225, null=True)),
                ('created_at_time', models.CharField(default='01:27:18 am', max_length=225, null=True)),
                ('ai', models.BooleanField(blank=True, default=False, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_projects_given', models.IntegerField(default=0)),
                ('number_of_projects_completed', models.IntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_projects', models.ManyToManyField(null=True, related_name='current_projects_of_client', to='api.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMsg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at_date', models.CharField(default='3rd December 2023', max_length=225, null=True)),
                ('created_at_time', models.CharField(default='01:27:18 am', max_length=225, null=True)),
                ('ai', models.BooleanField(blank=True, default=False, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
