# Generated by Django 4.2.7 on 2023-12-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_project_chat_group_id_project_workflow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmsg",
            name="created_at_time",
            field=models.CharField(default="8:03:14 pm", max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at_time",
            field=models.CharField(default="8:03:14 pm", max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="created_at_time",
            field=models.CharField(default="8:03:14 pm", max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.CharField(
                blank=True,
                default="4th December 2023 8:03:14 pm",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.CharField(
                blank=True,
                default="4th December 2023 8:03:14 pm",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.CharField(
                blank=True,
                default="4th December 2023 8:03:14 pm",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="learning_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.learningresource",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.CharField(
                blank=True,
                default="4th December 2023 8:03:14 pm",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.CharField(
                blank=True,
                default="4th December 2023 8:03:14 pm",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectmembers",
            name="role",
            field=models.CharField(
                choices=[
                    ("Leader", "Leader"),
                    ("Client", "Client"),
                    ("Mentor", "Mentor"),
                    ("Member", "Member"),
                ],
                default="Member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_at",
            field=models.CharField(
                blank=True,
                default="4th December 2023 8:03:14 pm",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="updated_at",
            field=models.CharField(
                blank=True,
                default="4th December 2023 8:03:14 pm",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
    ]
