# Generated by Django 4.2.7 on 2023-12-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_chatmsg_created_at_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectrequirementdocument",
            old_name="requirements_analysis",
            new_name="tech_stacks",
        ),
        migrations.RemoveField(
            model_name="project",
            name="learning_resource",
        ),
        migrations.AddField(
            model_name="project",
            name="Learning_resources",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Learning Resources"
            ),
        ),
        migrations.AddField(
            model_name="talent",
            name="learning_resources",
            field=models.JSONField(blank=True, default=list, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="chatmsg",
            name="created_at_date",
            field=models.CharField(
                default="6th December 2023", max_length=225, null=True
            ),
        ),
        migrations.AlterField(
            model_name="chatmsg",
            name="created_at_time",
            field=models.CharField(default="3:44:08 pm", max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at_date",
            field=models.CharField(
                default="6th December 2023", max_length=225, null=True
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at_time",
            field=models.CharField(default="3:44:08 pm", max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="created_at_date",
            field=models.CharField(
                default="6th December 2023", max_length=225, null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="created_at_time",
            field=models.CharField(default="3:44:08 pm", max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.CharField(
                blank=True,
                default="6th December 2023 3:44:08 pm",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.CharField(
                blank=True,
                default="6th December 2023 3:44:08 pm",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.CharField(
                blank=True,
                default="6th December 2023 3:44:08 pm",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.CharField(
                blank=True,
                default="6th December 2023 3:44:08 pm",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.CharField(
                blank=True,
                default="6th December 2023 3:44:08 pm",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectmembers",
            name="role",
            field=models.CharField(
                choices=[
                    ("Member", "Member"),
                    ("Leader", "Leader"),
                    ("Mentor", "Mentor"),
                    ("Client", "Client"),
                ],
                default="Member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_at",
            field=models.CharField(
                blank=True,
                default="6th December 2023 3:44:08 pm",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="updated_at",
            field=models.CharField(
                blank=True,
                default="6th December 2023 3:44:08 pm",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="LearningResource",
        ),
    ]
