# Generated by Django 4.2.7 on 2023-12-08 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_chatmsg_created_at_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="chatmsg",
            name="created_at_date",
            field=models.CharField(
                default="8th December 2023", max_length=225, null=True
            ),
        ),
        migrations.AlterField(
            model_name="chatmsg",
            name="created_at_time",
            field=models.CharField(default="10:49:38 am", max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at_date",
            field=models.CharField(
                default="8th December 2023", max_length=225, null=True
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at_time",
            field=models.CharField(default="10:49:38 am", max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="created_at_date",
            field=models.CharField(
                default="8th December 2023", max_length=225, null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="created_at_time",
            field=models.CharField(default="10:49:38 am", max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.CharField(
                blank=True,
                default="8th December 2023 10:49:38 am",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.CharField(
                blank=True,
                default="8th December 2023 10:49:38 am",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.CharField(
                blank=True,
                default="8th December 2023 10:49:38 am",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.CharField(
                blank=True,
                default="8th December 2023 10:49:38 am",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.CharField(
                blank=True,
                default="8th December 2023 10:49:38 am",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="workflow",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Workflow"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_at",
            field=models.CharField(
                blank=True,
                default="8th December 2023 10:49:38 am",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="api.project",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="updated_at",
            field=models.CharField(
                blank=True,
                default="8th December 2023 10:49:38 am",
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
    ]
