# Generated by Django 4.2.7 on 2023-12-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_chatmsg_created_at_date_and_more'),
        ('api', '0009_workflow_alter_chatmsg_created_at_date_and_more'),
    ]

    operations = [
    ]
